language: dart
dart:
- 2.0
- stable
- dev

addons:
  apt:
    packages:
    - elinks # Needs pygmentize -f html -O full

install:
- pip install --user pygments

script:
- dart2js --checked --enable-diagnostic-colors --out=hello.js hello.dart
- node hello.js

- dart2js --checked --enable-diagnostic-colors --out=fibonacci.js fibonacci.dart
- node fibonacci.js

- dart2js --checked --enable-diagnostic-colors --out=point.js point.dart
- node point.js

after_script:
- dart2js --verbose --help --enable-diagnostic-colors

- printenv TERM

- echo Short list
- pygmentize -P style=vim -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-color elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-88color elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-256color elinks -force-html -dump-color-mode 1 -dump # Best for js

- pygmentize -f 256 -P style=vim -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -f 256 -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-color elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -f 256 -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-88color elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -f 256 -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-256color elinks -force-html -dump-color-mode 1 -dump # Best for js

- pygmentize -f 16m -P style=vim -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -f 16m -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-color elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -f 16m -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-88color elinks -force-html -dump-color-mode 1 -dump # Best for js
- pygmentize -f 16m -P style=vim -f html -O full -P linenos=1 hello.js | env TERM=xterm-256color elinks -force-html -dump-color-mode 1 -dump # Best for js
