language: dart
dart:
- dev
- stable

install:
- pub get
- pip install --user pygments

script:
- dart2js --checked --enable-diagnostic-colors --out=hello.js hello.dart
- node hello.js

- dart2js --checked --enable-diagnostic-colors --out=fibonacci.js fibonacci.dart
- node fibonacci.js

- dart2js --checked --enable-diagnostic-colors --out=point.js point.dart
- node point.js

- dart2js --checked --enable-diagnostic-colors --out=print_arguments.dart2js print_arguments.dart
- cp /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js print_arguments.d8js
- cp /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js print_arguments.jsshell
- du -sch print_arguments.d8js print_arguments.jsshell print_arguments.dart2js
- cat print_arguments.dart2js >> print_arguments.d8js
- cat print_arguments.dart2js >> print_arguments.jsshell
- du -sch print_arguments.d8js print_arguments.jsshell
- dart print_arguments.dart Lot of arguments here!

- dart2js --checked --enable-diagnostic-colors --out=http_server.dart2js http_server.dart
- cp /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js http_server.d8js
- cp /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js http_server.jsshell
- du -sch http_server.d8js http_server.jsshell http_server.dart2js
- cat http_server.dart2js >> http_server.d8js
- cat http_server.dart2js >> http_server.jsshell
- du -sch http_server.d8js http_server.jsshell
- dart http_server.dart 8000 &
- printf 'HEAD /dart HTTP/1.1\r\n\r\n' | socat -T10 - TCP4:localhost:8000,forever >/dev/null # Waiting for server to connect.
- wget --quiet --connect-timeout=10 --output-document=- localhost:8000/dart

after_script:
- node --version
- command -v pub
- command -v dart
- command -v dart2js
- find . -name js_runtime
- find /home/travis/dart-sdk -name js_runtime
- ls --color /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles
- cat /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles/README
- cat /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js
- cat /home/travis/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js
- node print_arguments.d8js Lot of arguments here!
- node print_arguments.jsshell Lot of arguments here!
- node http_server.d8js &
- echo $?
# - printf 'HEAD /dart HTTP/1.1\r\n\r\n' | socat -T10 - TCP4:localhost:8888,forever >/dev/null # Waiting for server to connect.
# /home/travis/build/travis-util/dart2js-demo/http_server.d8js:263
# Unsupported operation: ServerSocket.bind
- wget --quiet --connect-timeout=10 --output-document=- localhost:8888/dart ; echo $?
# /home/travis/build/travis-util/dart2js-demo/http_server.js:3086
# ReferenceError: self is not defined

- pub deps
- pub --verbose --help --enable-diagnostic-colors
- dart --verbose --help --enable-diagnostic-colors
- dart2js --verbose --help --enable-diagnostic-colors

- printenv TERM

- echo dart2js produces hard to read js!
- cat hello.js
# - pygmentize -P style=vim -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump # Best for js
