language: dart
dart:
- stable
- dev

install:
- pip install --user pygments

script:
- dart2js --checked --enable-diagnostic-colors --out=point.js point.dart
- node point.js

after_script:
- dart2js --verbose --help --enable-diagnostic-colors

- pygmentize point.js
- pygmentize -O full point.js
- pygmentize -P style=friendly point.js
- pygmentize -P style=friendly -O full point.js

- pygmentize -f 16m point.js
- pygmentize -f 16m -O full point.js
- pygmentize -f 16m -P style=friendly point.js
- pygmentize -f 16m -P style=friendly -O full point.js

- pygmentize -f 256 point.js
- pygmentize -f 256 -O full point.js
- pygmentize -f 256 -P style=friendly point.js
- pygmentize -f 256 -P style=friendly -O full point.js
