language: dart
dart:
- stable
- dev

addons:
  apt:
    packages:
    - elinks # Needs pygmentize -f html -O full

install:
- pip install --user pygments

script:
- dart2js --checked --enable-diagnostic-colors --out=hello.js hello.dart
- node hello.js

- dart2js --checked --enable-diagnostic-colors --out=fibonacci.js fibonacci.dart
- node fibonacci.js

- dart2js --checked --enable-diagnostic-colors --out=point.js point.dart
- node point.js

after_script:
- dart2js --verbose --help --enable-diagnostic-colors

- printenv TERM

- pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 16 -dump
- pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 88 -dump
- pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 256 -dump

- env TERM=xterm-color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump
- env TERM=xterm-color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump

- env TERM=xterm-88color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump
- env TERM=xterm-88color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump

- env TERM=xterm-256color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump
- env TERM=xterm-256color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump

- pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump
- pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 16 -dump
- pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 88 -dump
- pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 256 -dump

- pygmentize point.js
- pygmentize -O full point.js
- pygmentize -P style=friendly point.js
- pygmentize -P style=friendly -O full point.js

- pygmentize -f 16m point.js
- pygmentize -f 16m -O full point.js
- pygmentize -f 16m -P style=friendly point.js
- pygmentize -f 16m -P style=friendly -O full point.js

- pygmentize -f 256 point.js
- pygmentize -f 256 -O full point.js
- pygmentize -f 256 -P style=friendly point.js
- pygmentize -f 256 -P style=friendly -O full point.js
