language: dart
dart:
- stable
- dev

addons:
  apt:
    packages:
    - elinks # Needs pygmentize -f html -O full

install:
- pip install --user pygments

script:
- dart2js --checked --enable-diagnostic-colors --out=hello.js hello.dart
- node hello.js

- dart2js --checked --enable-diagnostic-colors --out=fibonacci.js fibonacci.dart
- node fibonacci.js

- dart2js --checked --enable-diagnostic-colors --out=point.js point.dart
- node point.js

after_script:
- dart2js --verbose --help --enable-diagnostic-colors

- printenv TERM

- echo Short list
- pygmentize -P style=vim -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=native -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=fruity -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P style=manni -f 256 hello.js
- pygmentize -P style=perldoc -f 16m hello.js
- pygmentize -P style=rainbow_dash -f 256 hello.js

- echo Comprenhensive list
- pygmentize -P linenos=1 -P bg=dark hello.js
- pygmentize -P linenos=1 hello.js
- pygmentize -P linenos=1 -f html -O full hello.js | elinks -force-html -dump-color-mode 0 -dump
- pygmentize -P linenos=1 -f html -O full hello.js | elinks -force-html -dump-color-mode 1 -dump
- pygmentize -P linenos=1 -f html -O full hello.js | elinks -force-html -dump-color-mode 2 -dump
- pygmentize -P linenos=1 -f html -O full hello.js | elinks -force-html -dump-color-mode 3 -dump
- pygmentize -P linenos=1 -f html -O full hello.js | elinks -force-html -dump-color-mode 4 -dump

- pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- env TERM=xterm-color pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- env TERM=xterm-88color pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- env TERM=xterm-256color pygmentize -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump

- pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- env TERM=xterm-color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- env TERM=xterm-88color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump
- env TERM=xterm-256color pygmentize -P style=friendly -f html -O full -P linenos=1 point.js  | elinks -force-html -dump-color-mode 1 -dump


- pygmentize point.js
- pygmentize -O full point.js
- pygmentize -P style=friendly point.js
- pygmentize -P style=friendly -O full point.js

- pygmentize -f 16m point.js
- pygmentize -f 16m -O full point.js
- pygmentize -f 16m -P style=friendly point.js
- pygmentize -f 16m -P style=friendly -O full point.js

- pygmentize -f 256 point.js
- pygmentize -f 256 -O full point.js
- pygmentize -f 256 -P style=friendly point.js
- pygmentize -f 256 -P style=friendly -O full point.js
