language: dart
dart:
- dev
- stable

install:
- pip install --user pygments

script:
- dart2js --checked --enable-diagnostic-colors --out=hello.js hello.dart
- node hello.js

- dart2js --checked --enable-diagnostic-colors --out=fibonacci.js fibonacci.dart
- node fibonacci.js

- dart2js --checked --enable-diagnostic-colors --out=point.js point.dart
- node point.js

after_script:
- dart2js --verbose --help --enable-diagnostic-colors

- printenv TERM

- echo dart2js produces hard to read js:
- cat hello.js
# - pygmentize -P style=vim -f html -O full -P linenos=1 hello.js | elinks -force-html -dump-color-mode 1 -dump # Best for js
