language: dart
dart:
- stable
- dev

script:
- dart2js --checked --enable-diagnostic-colors --out=point.js point.dart
- cat point.js

after_script:
- dart2js --verbose --help --enable-diagnostic-colors
